databases:
  - name: RooMic
    databaseName: roomic
    user: roomic_user

services:
  - type: web
    name: RooMic App
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: RooMic
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false